---
  header_logo_url: http://coreoidea.speciesfile.org/HomePage/Coreoidea/img_Logo/SiteLogo.jpg
  header_logo_text: Coreoidea Species File Online
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
